#pragma once
#include <array>
#include <string_view>

namespace codon {

  struct Transmuter {
    std::string_view dna;
    std::string_view rna;
    std::string_view prot_w;
    char prot;
  };

  inline constexpr std::array<Transmuter, 85> _transmute_arr{{
    {"VOID","VOID",  "-", '-'},
    {  "A",   "A",   "-", '-'},
    {  "G",   "G",   "-", '-'},
    {  "C",   "C",   "-", '-'},
    {  "T",   "U",   "-", '-'},
    { "AA",  "AA",   "-", '-'},
    { "AG",  "AG",   "-", '-'},
    { "AC",  "AC",   "-", '-'},
    { "AT",  "AU",   "-", '-'},
    { "GA",  "GA",   "-", '-'},
    { "GG",  "GG",   "-", '-'},
    { "GC",  "GC",   "-", '-'},
    { "GT",  "GU",   "-", '-'},
    { "CA",  "CA",   "-", '-'},
    { "CG",  "CG",   "-", '-'},
    { "CC",  "CC",   "-", '-'},
    { "CT",  "CU",   "-", '-'},
    { "TA",  "UA",   "-", '-'},
    { "TG",  "UG",   "-", '-'},
    { "TC",  "UC",   "-", '-'},
    { "TT",  "UU",   "-", '-'},
    { "AAA", "AAA", "Lys", 'K'},
    { "AAG", "AAG", "Lys", 'K'},
    { "AAC", "AAC", "Asn", 'N'},
    { "AAT", "AAU", "Asn", 'N'},
    { "AGA", "AGA", "Arg", 'R'},
    { "AGG", "AGG", "Arg", 'R'},
    { "AGC", "AGC", "Ser", 'S'},
    { "AGT", "AGU", "Ser", 'S'},
    { "ACA", "ACA", "Thr", 'T'},
    { "ACG", "ACG", "Thr", 'T'},
    { "ACC", "ACC", "Thr", 'T'},
    { "ACT", "ACU", "Thr", 'T'},
    { "ATA", "AUA", "Ile", 'I'},
    { "ATG", "AUG", "Met", 'M'},
    { "ATC", "AUC", "Ile", 'I'},
    { "ATT", "AUU", "Ile", 'I'},
    { "GAA", "GAA", "Glu", 'E'},
    { "GAG", "GAG", "Glu", 'E'},
    { "GAC", "GAC", "Asp", 'D'},
    { "GAT", "GAU", "Asp", 'D'},
    { "GGA", "GGA", "Gly", 'G'},
    { "GGG", "GGG", "Gly", 'G'},
    { "GGC", "GGC", "Gly", 'G'},
    { "GGT", "GGU", "Gly", 'G'},
    { "GCA", "GCA", "Ala", 'A'},
    { "GCG", "GCG", "Ala", 'A'},
    { "GCC", "GCC", "Ala", 'A'},
    { "GCT", "GCU", "Ala", 'A'},
    { "GTA", "GUA", "Val", 'V'},
    { "GTG", "GUG", "Val", 'V'},
    { "GTC", "GUC", "Val", 'V'},
    { "GTT", "GUU", "Val", 'V'},
    { "CAA", "CAA", "Gln", 'Q'},
    { "CAG", "CAG", "Gln", 'Q'},
    { "CAC", "CAC", "His", 'H'},
    { "CAT", "CAU", "His", 'H'},
    { "CGA", "CGA", "Arg", 'R'},
    { "CGG", "CGG", "Arg", 'R'},
    { "CGC", "CGC", "Arg", 'R'},
    { "CGT", "CGU", "Arg", 'R'},
    { "CCA", "CCA", "Pro", 'P'},
    { "CCG", "CCG", "Pro", 'P'},
    { "CCC", "CCC", "Pro", 'P'},
    { "CCT", "CCU", "Pro", 'P'},
    { "CTA", "CUA", "Leu", 'L'},
    { "CTG", "CUG", "Leu", 'L'},
    { "CTC", "CUC", "Leu", 'L'},
    { "CTT", "CUU", "Leu", 'L'},
    { "TAA", "UAA", "Ter", 'X'},
    { "TAG", "UAG", "Ter", 'X'},
    { "TAC", "UAC", "Tyr", 'Y'},
    { "TAT", "UAU", "Tyr", 'Y'},
    { "TGA", "UGA", "Ter", 'X'},
    { "TGG", "UGG", "Trp", 'W'},
    { "TGC", "UGC", "Cys", 'C'},
    { "TGT", "UGU", "Cys", 'C'},
    { "TCA", "UCA", "Ser", 'S'},
    { "TCG", "UCG", "Ser", 'S'},
    { "TCC", "UCC", "Ser", 'S'},
    { "TCT", "UCU", "Ser", 'S'},
    { "TTA", "UUA", "Leu", 'L'},
    { "TTG", "UUG", "Leu", 'L'},
    { "TTC", "UUC", "Phe", 'F'},
    { "TTT", "UUU", "Phe", 'F'},
  }};
}// namespace codon

